/*
  File autogenerated by gengetopt version 2.22.5
  generated with the following command:
  gengetopt -i gbs_digest.ggo -a args_info -f parser --unamed-opts 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline.h"

const char *args_info_purpose = "";

const char *args_info_usage = "Usage: gbs_digest [OPTIONS]... [FILES]...";

const char *args_info_description = "Split reads using motif (e.g. CAGT). Regular expression such as \n\"GATC|[AG](CATG)[CT]\" is also accepted with quotes.";

const char *args_info_help[] = {
  "  -h, --help     Print help and exit",
  "  -V, --version  Print version and exit",
    0
};

typedef enum {ARG_NO
} parser_arg_type;

static
void clear_given (struct args_info *args_info);
static
void clear_args (struct args_info *args_info);

static int
parser_internal (int argc, char **argv, struct args_info *args_info,
                        struct parser_params *params, const char *additional_error);


static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
}

static
void clear_args (struct args_info *args_info)
{
  FIX_UNUSED (args_info);
  
}

static
void init_args_info(struct args_info *args_info)
{


  args_info->help_help = args_info_help[0] ;
  args_info->version_help = args_info_help[1] ;
  
}

void
parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(PARSER_PACKAGE_NAME) ? PARSER_PACKAGE_NAME : PARSER_PACKAGE),
     PARSER_VERSION);
}

static void print_help_common(void) {
  parser_print_version ();

  if (strlen(args_info_purpose) > 0)
    printf("\n%s\n", args_info_purpose);

  if (strlen(args_info_usage) > 0)
    printf("\n%s\n", args_info_usage);

  printf("\n");

  if (strlen(args_info_description) > 0)
    printf("%s\n\n", args_info_description);
}

void
parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (args_info_help[i])
    printf("%s\n", args_info_help[i++]);
}

void
parser_init (struct args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = 0;
  args_info->inputs_num = 0;
}

void
parser_params_init(struct parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct parser_params *
parser_params_create(void)
{
  struct parser_params *params = 
    (struct parser_params *)malloc(sizeof(struct parser_params));
  parser_params_init(params);  
  return params;
}



static void
parser_release (struct args_info *args_info)
{
  unsigned int i;
  
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);

  if (args_info->inputs_num)
    free (args_info->inputs);

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
parser_dump(FILE *outfile, struct args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
parser_file_save(const char *filename, struct args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
parser_free (struct args_info *args_info)
{
  parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
parser (int argc, char **argv, struct args_info *args_info)
{
  return parser2 (argc, argv, args_info, 0, 1, 1);
}

int
parser_ext (int argc, char **argv, struct args_info *args_info,
                   struct parser_params *params)
{
  int result;
  result = parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
parser2 (int argc, char **argv, struct args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
parser_required (struct args_info *args_info, const char *prog_name)
{
  FIX_UNUSED (args_info);
  FIX_UNUSED (prog_name);
  return EXIT_SUCCESS;
}


static char *package_name = 0;



int
parser_internal (
  int argc, char **argv, struct args_info *args_info,
                        struct parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    parser_init (args_info);

  parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hV", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          parser_print_help ();
          parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          parser_print_version ();
          parser_free (&local_args_info);
          exit (EXIT_SUCCESS);


        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */




  parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  
  parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
